from __future__ import annotations

from typing import Any

DEFAULT_SENSITIVE_TERMS: list[dict[str, Any]] = [
    # 平台/竞品词：标题、图片提示词、素材文案里不应出现平台名或竞品平台名。
    {"term": "temu", "language": "en", "category": "platform", "severity": "block", "replacement": ""},
    {"term": "amazon", "language": "en", "category": "platform", "severity": "block", "replacement": ""},
    {"term": "shein", "language": "en", "category": "platform", "severity": "block", "replacement": ""},
    {"term": "tiktok", "language": "en", "category": "platform", "severity": "block", "replacement": ""},
    {"term": "抖音", "language": "zh", "category": "platform", "severity": "block", "replacement": ""},
    {"term": "淘宝", "language": "zh", "category": "platform", "severity": "block", "replacement": ""},
    {"term": "拼多多", "language": "zh", "category": "platform", "severity": "block", "replacement": ""},
    {"term": "亚马逊", "language": "zh", "category": "platform", "severity": "block", "replacement": ""},
    # 品牌/IP/版权词：避免侵权、蹭品牌、图片生成时出现角色或 Logo。
    {"term": "disney", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "marvel", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "pokemon", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "pokémon", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "hello kitty", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "sanrio", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "nike", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "adidas", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "apple", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "iphone", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "supreme", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "gucci", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "lv", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "louis vuitton", "language": "en", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "迪士尼", "language": "zh", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "漫威", "language": "zh", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "宝可梦", "language": "zh", "category": "brand_ip", "severity": "block", "replacement": ""},
    {"term": "凯蒂猫", "language": "zh", "category": "brand_ip", "severity": "block", "replacement": ""},
    # 绝对化营销词：避免夸大、最低价、保证等风险词。
    {"term": "best", "language": "en", "category": "absolute_marketing", "severity": "replace", "replacement": "popular"},
    {"term": "number one", "language": "en", "category": "absolute_marketing", "severity": "replace", "replacement": "popular"},
    {"term": "#1", "language": "en", "category": "absolute_marketing", "severity": "replace", "replacement": "popular"},
    {"term": "guaranteed", "language": "en", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    {"term": "100%", "language": "mixed", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    {"term": "lowest price", "language": "en", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    {"term": "最", "language": "zh", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    {"term": "第一", "language": "zh", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    {"term": "全网最低", "language": "zh", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    {"term": "最低价", "language": "zh", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    {"term": "保证", "language": "zh", "category": "absolute_marketing", "severity": "block", "replacement": ""},
    # 官方/资质/认证词：没有真实证明时不写。
    {"term": "official", "language": "en", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "authentic", "language": "en", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "patented", "language": "en", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "certified", "language": "en", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "fda", "language": "en", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "ce certified", "language": "en", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "正品", "language": "zh", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "官方", "language": "zh", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "专利", "language": "zh", "category": "certification_claim", "severity": "block", "replacement": ""},
    {"term": "认证", "language": "zh", "category": "certification_claim", "severity": "block", "replacement": ""},
    # 医疗/健康功效词：非医疗商品一律降级或删除。
    {"term": "medical", "language": "en", "category": "medical_claim", "severity": "replace", "replacement": "daily-use"},
    {"term": "cure", "language": "en", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "treat", "language": "en", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "therapy", "language": "en", "category": "medical_claim", "severity": "replace", "replacement": "comfort"},
    {"term": "therapeutic", "language": "en", "category": "medical_claim", "severity": "replace", "replacement": "comfort"},
    {"term": "antibacterial", "language": "en", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "anti-bacterial", "language": "en", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "antivirus", "language": "en", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "anti-virus", "language": "en", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "sterilize", "language": "en", "category": "medical_claim", "severity": "replace", "replacement": "clean"},
    {"term": "sterilization", "language": "en", "category": "medical_claim", "severity": "replace", "replacement": "clean"},
    {"term": "医用", "language": "zh", "category": "medical_claim", "severity": "replace", "replacement": "日用"},
    {"term": "治疗", "language": "zh", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "治愈", "language": "zh", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "杀菌", "language": "zh", "category": "medical_claim", "severity": "replace", "replacement": "易清洁"},
    {"term": "抗菌", "language": "zh", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "抗病毒", "language": "zh", "category": "medical_claim", "severity": "block", "replacement": ""},
    {"term": "消毒", "language": "zh", "category": "medical_claim", "severity": "replace", "replacement": "清洁"},
    # 危险/成人限制：默认屏蔽，不用于普通 Temu 商品标题和生图提示词。
    {"term": "weapon", "language": "en", "category": "restricted_goods", "severity": "block", "replacement": ""},
    {"term": "knife", "language": "en", "category": "restricted_goods", "severity": "block", "replacement": ""},
    {"term": "gun", "language": "en", "category": "restricted_goods", "severity": "block", "replacement": ""},
    {"term": "adult", "language": "en", "category": "restricted_goods", "severity": "block", "replacement": ""},
    {"term": "武器", "language": "zh", "category": "restricted_goods", "severity": "block", "replacement": ""},
    {"term": "刀具", "language": "zh", "category": "restricted_goods", "severity": "block", "replacement": ""},
    {"term": "枪", "language": "zh", "category": "restricted_goods", "severity": "block", "replacement": ""},
    {"term": "成人用品", "language": "zh", "category": "restricted_goods", "severity": "block", "replacement": ""},
]
